# -*- coding: utf-8 -*-
"""video2text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rut9X76IEb7iQSfeEIhTLYnVPyAY_w8N
"""

!pip install openai
!pip install -U openai-whisper
!pip install langchain
!pip install pytube

import pytube as pt
yt=pt.YouTube("https://www.youtube.com/watch?v=hTfTsImtRxA")
stream=yt.streams.filter(only_audio=True)[0]
stream.download(filename="yt_audio.mp3")

import whisper
model = whisper.load_model("base")
result = model.transcribe("yt_audio.mp3")
text = result['text']
print(text)

from langchain import OpenAI, LLMChain
from langchain.chains.summerize import load_summerize_chain
from langchain.splitter import RecursiveCharacterTextSplitter

llm = OpenAI(model_name='text-davinci-003',openai_api_key = 'key')

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=1000, chunk_overlap=0, separators=[" ",",","\n"]
)

texts = text_splitter.split_text(text)
print(texts)

docs = text_splitter.create_documents(text)
print(docs)
chain = load_summerize_chain(llm, chain_type = "map_reduce")

output_summary = chain.run(docs)